# Generated by Django 4.2.9 on 2024-02-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.IntegerField(default=10),
        ),
    ]
