# Generated by Django 4.2.9 on 2024-03-01 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_listing_image_listing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
